name: manager_room_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  uuid: ^4.0.0

  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.9.1

  # Flutter Secure Storage
  flutter_secure_storage: ^9.2.4

  # Image Picker
  image_picker: ^1.1.2

  # Image Compress
  flutter_image_compress: ^2.3.0

  # crypt
  crypto: ^3.0.3

  # Shared Preferences
  shared_preferences: ^2.2.2

  # file picker
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
